"""Add students table with all fields

Revision ID: 9a40d4635286
Revises: 
Create Date: 2026-03-03 14:08:28.570300

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9a40d4635286'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('students', schema=None) as batch_op:
        batch_op.add_column(sa.Column('clearance_form_verified', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('clearance_form_verified_by', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('clearance_form_verified_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('admission_letter_verified', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('admission_letter_verified_by', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('admission_letter_verified_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('documents_verified', sa.Boolean(), nullable=True))
        batch_op.create_foreign_key('fk_students_clearance_verified_by', 'users', ['clearance_form_verified_by'], ['id'])
        batch_op.create_foreign_key('fk_students_admission_verified_by', 'users', ['admission_letter_verified_by'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('students', schema=None) as batch_op:
        batch_op.drop_constraint('fk_students_admission_verified_by', type_='foreignkey')
        batch_op.drop_constraint('fk_students_clearance_verified_by', type_='foreignkey')
        batch_op.drop_column('documents_verified')
        batch_op.drop_column('admission_letter_verified_at')
        batch_op.drop_column('admission_letter_verified_by')
        batch_op.drop_column('admission_letter_verified')
        batch_op.drop_column('clearance_form_verified_at')
        batch_op.drop_column('clearance_form_verified_by')
        batch_op.drop_column('clearance_form_verified')

    # ### end Alembic commands ###
